version: '2'

services:
  mongo:
    image: mongo:3.7.2
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf:ro
      - ./redis.conf:/usr/local/etc/redis/redis.conf

