version: '2'

services:
  mongo:
    image: mongo:3.7.2
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  redis:
    image: redis:4.0.8-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
